export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  DEVELOPER = 'DEVELOPER',
  AGENT = 'AGENT',
  BROKER = 'BROKER',
  PROPERTY_OWNER = 'PROPERTY_OWNER',
  BUYER = 'BUYER',
  TENANT = 'TENANT',
  PURCHASER = 'PURCHASER', // Backward compatibility alias for BUYER
  VERIFIED_AGENT = 'VERIFIED_AGENT', // Backward compatibility alias for AGENT
  GUEST = 'GUEST',
}

export enum AccountType {
  DEVELOPER = 'DEVELOPER',
  AGENT = 'AGENT',
  BROKER = 'BROKER',
  PROPERTY_OWNER = 'PROPERTY_OWNER',
  BUYER = 'BUYER',
  TENANT = 'TENANT',
}

export enum AccountStatus {
  ACTIVE = 'ACTIVE',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  SUSPENDED = 'SUSPENDED',
  DEACTIVATED = 'DEACTIVATED',
}

export enum OtpStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  EXPIRED = 'EXPIRED',
  LOCKED = 'LOCKED',
}
