export enum LeadStatus {
  NEW = 'NEW',
  CONTACTED = 'CONTACTED',
  FOLLOW_UP = 'FOLLOW_UP',
  QUALIFIED = 'QUALIFIED',
  INTERESTED = 'INTERESTED',
  SITE_VISIT = 'SITE_VISIT',
  NEGOTIATION = 'NEGOTIATION',
  CONVERTED = 'CONVERTED',
  LOST = 'LOST',
  CANCELLED = 'CANCELLED',
  CLOSED = 'CLOSED',
}

export enum LeadPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum LeadSource {
  PROPERTY_ENQUIRY = 'PROPERTY_ENQUIRY',
  PROPERTY_PAGE = 'PROPERTY_PAGE',
  DIRECT = 'DIRECT',
  WHATSAPP = 'WHATSAPP',
  CALL = 'CALL',
  PHONE = 'PHONE',
  WEBSITE = 'WEBSITE',
  REFERRAL = 'REFERRAL',
  CAMPAIGN = 'CAMPAIGN',
  CONTACT_FORM = 'CONTACT_FORM',
  SEARCH = 'SEARCH',
  OTHER = 'OTHER',
}

export enum ActivityType {
  NOTE = 'NOTE',
  CALL = 'CALL',
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
  SITE_VISIT = 'SITE_VISIT',
  STATUS_CHANGE = 'STATUS_CHANGE',
  ASSIGNMENT = 'ASSIGNMENT',
  FOLLOW_UP = 'FOLLOW_UP',
  OTHER = 'OTHER',
}

export enum FollowUpType {
  CALL = 'CALL',
  WHATSAPP = 'WHATSAPP',
  EMAIL = 'EMAIL',
  SITE_VISIT = 'SITE_VISIT',
  MEETING = 'MEETING',
  OTHER = 'OTHER',
}

export enum FollowUpStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
